
// Audio effects
const sound = {
                "p_hpf_freq": 0.104,
                "p_duty": 0.457,
                "p_pha_offset": 0.142,
                "p_env_sustain": 0.047,
                "wave_type": 2,
                "preset": "click",
                "p_lpf_freq": 1,
                "p_env_decay": 0.467,
                "sample_size": 8,
                "p_arp_speed": 0,
                "p_vib_speed": 0,
                "p_freq_limit": 0,
                "p_vib_strength": 1,
                "p_pha_ramp": 0.526,
                "p_lpf_ramp": 0,
                "p_lpf_resonance": 0.633,
                "name": null,
                "p_base_freq": 0.348,
                "p_hpf_ramp": 0,
                "ctime": 1674601289935,
                "p_repeat_speed": 0,
                "p_freq_ramp": -0.47,
                "sound_vol": 0.25,
                "p_arp_mod": -1,
                "p_env_punch": 0.083,
                "oldParams": true,
                "p_env_attack": 0,
                "p_freq_dramp": -1,
                "sample_rate": 22050,
                "p_duty_ramp": 0.537,
                "mtime": 1674604666633
                }