services:
  proxy:
    image: nginx
    container_name: nginx_proxy
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "5555:80"
    depends_on:
      - backend

  backend: 
    build:
      context: ./backend
    container_name: yinsh_service
