services:
  
  # NGINX as reverse proxy
  nginx:
    image: nginx
    container_name: nginx-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    #command: /bin/ash -c "exec nginx -g 'daemon off;'"
    #command: /bin/ash -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & exec nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  # for handling certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
   #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"

  # yinsh service
  backend: 
    build:
      context: ./backend
    container_name: yinsh-service
