# https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
# https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
# https://stackoverflow.com/questions/38567355/docker-compose-global-level-logging
# https://docs.docker.com/engine/logging/drivers/local/
# https://stackoverflow.com/a/75245637 (cpu/memory limits, docker compose vs docker-compose)

services:
  
  # NGINX as reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/frontend:/var/frontend
      - ./data/certs:/var/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - yinsh_server
    logging:
      driver: "local"
      options:
        max-size: "10m" # 10MB
        max-file: "5"  # 5 rotating files
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 250m


  # yinsh service
  backend: 
    build:
      context: ./yinsh_server
    container_name: yinsh_server
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"  
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
      

