# https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
# https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines

services:
  
  # NGINX as reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/frontend:/var/frontend
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: /bin/ash -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & exec nginx -g 'daemon off;'" # after cert issuing
      # /bin/ash -c "exec nginx -g 'daemon off;'" # to be used for issuing certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  # for handling certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'" # after cert issuing

  # yinsh service
  backend: 
    build:
      context: ./backend
    container_name: yinsh-service
