# https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
# https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines

services:
  
  # NGINX as reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/frontend:/var/frontend
      - ./data/certs:/var/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend


  # yinsh service
  backend: 
    build:
      context: ./backend
    container_name: yinsh-service
